"""add email verification

Revision ID: add_email_verification
Revises: add_enhanced_notifications
Create Date: 2024-01-20 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'add_email_verification'
down_revision = 'add_enhanced_notifications'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.String(length=120),
               nullable=True)
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('email_verification_code', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('email_verification_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verification_expiry')
    op.drop_column('users', 'email_verification_code')
    op.drop_column('users', 'email_verified')
    op.alter_column('users', 'email',
               existing_type=sa.String(length=120),
               nullable=False)
    # ### end Alembic commands ###
