apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: beta
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"

    output.elasticsearch:
      hosts: ["elasticsearch-beta:9200"]
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}

    setup.kibana:
      host: "kibana-beta:5601"

    setup.dashboards.enabled: true
    setup.template.enabled: true

    logging.json: true
    logging.metrics.enabled: true
