name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          npm ci
          npm run bootstrap
          cd packages/backend && pip install -r requirements.txt
          cd ../..

      - name: Generate coverage reports
        run: npm run coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=richardfosterpersonal
            -Dsonar.projectKey=meditracker-beta
            -Dsonar.python.coverage.reportPaths=packages/backend/coverage.xml
            -Dsonar.javascript.lcov.reportPaths=packages/frontend/coverage/lcov.info,packages/core/coverage/lcov.info,packages/shared/coverage/lcov.info
            -Dsonar.sources=packages/frontend/src,packages/backend/app,packages/core/src,packages/shared/src
            -Dsonar.tests=packages/frontend/src/__tests__,packages/backend/tests,packages/core/src/__tests__,packages/shared/src/__tests__
            -Dsonar.test.inclusions=**/*.test.ts,**/*.spec.ts,**/tests/**,**/__tests__/**
            -Dsonar.coverage.exclusions=**/*.test.ts,**/*.spec.ts,**/tests/**,**/__tests__/
