apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: production
data:
  01-init.sql: |
    -- Enable required extensions
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    CREATE EXTENSION IF NOT EXISTS "pgcrypto";
    CREATE EXTENSION IF NOT EXISTS "citext";
    
    -- Set up connection pooling
    ALTER SYSTEM SET max_connections = '200';
    ALTER SYSTEM SET shared_buffers = '1GB';
    ALTER SYSTEM SET effective_cache_size = '3GB';
    ALTER SYSTEM SET work_mem = '16MB';
    ALTER SYSTEM SET maintenance_work_mem = '256MB';
    
    -- Set up statement timeout for safety
    ALTER SYSTEM SET statement_timeout = '30s';
    
    -- Enable connection tracking
    ALTER SYSTEM SET log_connections = 'on';
    ALTER SYSTEM SET log_disconnections = 'on';
    
    -- Set up WAL for point-in-time recovery
    ALTER SYSTEM SET wal_level = 'replica';
    ALTER SYSTEM SET archive_mode = 'on';
    ALTER SYSTEM SET archive_command = 'test ! -f /var/lib/postgresql/archive/%f && cp %p /var/lib/postgresql/archive/%f';
    
    -- Create readonly user for reporting
    CREATE USER readonly_user WITH PASSWORD '${READONLY_PASSWORD}';
    GRANT CONNECT ON DATABASE medminder_prod TO readonly_user;
    GRANT USAGE ON SCHEMA public TO readonly_user;
    GRANT SELECT ON ALL TABLES IN SCHEMA public TO readonly_user;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO readonly_user;
