apiVersion: v1
kind: Secret
metadata:
  name: medminder-secrets
  namespace: production
type: Opaque
stringData:
  # Database
  database-url: "postgresql://medminder_prod:${DB_PASSWORD}@prod-db.medminder.pro:5432/medminder_prod?schema=public"
  
  # Redis
  redis-url: "redis://:${REDIS_PASSWORD}@prod-redis.medminder.pro:6379"
  
  # JWT
  jwt-secret: "${JWT_SECRET}"
  
  # Sentry
  sentry-dsn: "${SENTRY_DSN}"
  
  # API Keys
  fda-api-key: "${FDA_API_KEY}"
  nccih-api-key: "${NCCIH_API_KEY}"
  
  # Email
  smtp-host: "smtp.medminder.pro"
  smtp-user: "notifications@medminder.pro"
  smtp-password: "${SMTP_PASSWORD}"
  
  # SMS
  twilio-account-sid: "${TWILIO_ACCOUNT_SID}"
  twilio-auth-token: "${TWILIO_AUTH_TOKEN}"
  twilio-phone-number: "${TWILIO_PHONE_NUMBER}"
