apiVersion: v1
kind: Secret
metadata:
  name: beta-secrets
  namespace: beta
type: Opaque
stringData:
  # Database configuration
  database-url: postgresql://user:password@postgres-beta:5432/medication_tracker_beta
  
  # Application secrets
  jwt-secret: <replace-with-secure-jwt-secret>
  encryption-key: <replace-with-secure-encryption-key>
  
  # API keys
  notification-api-key: <replace-with-notification-api-key>
  monitoring-api-key: <replace-with-monitoring-api-key>
  
  # Beta-specific secrets
  beta-admin-password: <replace-with-beta-admin-password>
  feedback-system-key: <replace-with-feedback-system-key>
---
apiVersion: v1
kind: Secret
metadata:
  name: beta-db-secrets
  namespace: beta
type: Opaque
stringData:
  username: beta_db_user
  password: <replace-with-secure-db-password>
