apiVersion: batch/v1
kind: CronJob
metadata:
  name: beta-db-backup
  namespace: beta
spec:
  schedule: "0 */6 * * *"  # Every 6 hours
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: postgres:15
            command:
            - /bin/sh
            - -c
            - |
              pg_dump -h postgres-beta -U $POSTGRES_USER -d medication_tracker_beta > /backup/beta-db-$(date +%Y%m%d_%H%M%S).sql
            env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: beta-db-secrets
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: beta-db-secrets
                  key: password
            volumeMounts:
            - name: backup-volume
              mountPath: /backup
          volumes:
          - name: backup-volume
            persistentVolumeClaim:
              claimName: beta-backup-pvc
          restartPolicy: OnFailure
