apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: beta
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'medication-tracker-beta'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - beta
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: medication-tracker-beta
            action: keep
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            regex: "8080"
            action: keep

      - job_name: 'beta-database'
        static_configs:
          - targets: ['postgres-beta:5432']
        metrics_path: /metrics

      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: kubernetes_node
