version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.beta
    container_name: medminder_frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/app
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
    environment:
      - NODE_ENV=beta
      - REACT_APP_API_URL=https://api.getmedminder.com
      - REACT_APP_FIREBASE_CONFIG=${FIREBASE_CONFIG}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.beta
    container_name: medminder_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./logs:/app/logs
    environment:
      - ENVIRONMENT=beta
      - DATABASE_URL=${DATABASE_URL}
      - FIREBASE_CONFIG=${FIREBASE_CONFIG}
      - SSL_ENABLED=true
      - DOMAIN=getmedminder.com
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:13
    container_name: medminder_db
    environment:
      - POSTGRES_DB=medminder
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d medminder"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    container_name: medminder_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: medminder_network
